### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by stufraser1** [OasisLMF/OpenDataTransform#36]
@OmegaDroid CSV file contains the operators and fields we would like to include as examples of data validation. 
This is not a comprehensive list, but intended to provide enough examples to build the validation logic, and provide examples so users can replicate the logic later with other specific cases. 
We think the definition of fields to validate, and operators to use should sit in the mapping file to be defined by the creator of the mapping file.
A full set of operators should be included in the available logic.

@benhayes21 proposes something like this, but we would like your views on this please.
![image](https://user-images.githubusercontent.com/12515042/146534145-a5cbb642-9ee4-4ff6-ac41-fc253bb5afa9.png)

Reporting of data validation is to be discussed.
A standard reporting template would be ideal but the flexible configuration, allowing users to select which fields to validate does mean we might not achieve a consistent set of fields being reported. We'd like to discuss how to implement this to achieve a balance between achieving standardised reporting and flexibility for users.

**Comment by OmegaDroid** [comment]
@stufraser1 I think we may need to create a new file type. The issue with having them on the mapping would require them to be implemented multiple times with possible differences (for instance many files will map to OED).

I'd suggest we create a summaries file that contains the spec for a single format.

**Comment by OmegaDroid** [comment]
With the `PortfolioTIVbyConstruction`, there are multiple fields, how should these be treated, are they added together per row and summed across the portfolio or do we want a separate entry per field?

**Comment by OmegaDroid** [comment]
@stufraser1 Is there going to be any need for transformations here? Not sure if applicable but I'm thinking of values being stored in different denominations eg values in pounds vs values in thousands of pounds.

We could leave these up to the user to convert but it seems like we could transform it within the tool.

**Comment by stufraser1** [comment]
> 

Do you mean, the validation for loc file would sit in Loc mapping file,  validation for Acc file would sit in Acc mapping file, etc? Yes I guess that would be the case which we hadn't considered. Good point, if it is overall better to manage this in one validation file, then that would also work. Users would be required to fields implemented in the mapping file, but comparing across two files is OK.

**Comment by stufraser1** [comment]
> With the `PortfolioTIVbyConstruction`, there are multiple fields, how should these be treated, are they added together per row and summed across the portfolio or do we want a separate entry per field?

There should be a value returned for each of the four values (building, content, TimeElement, Other)

**Comment by stufraser1** [comment]
> Is there going to be any need for transformations here? Not sure if applicable but I'm thinking of values being stored in different denominations eg values in pounds vs values in thousands of pounds. We could leave these up to the user to convert but it seems like we could transform it within the tool.

No need for transformation - Any transformation would occur in the mapping file. This process is only to check the mapping worked properly so should compare the two values as they are. If the values are changed by a certain factor, that should show up in the validation by the values being different  - users will know / can then check if that is correct.
