### ISSUE TITLE
UI - filepath memory

### ISSUE THREAD

**Issue by stufraser1** [OasisLMF/OpenDataTransform#62]
File browser navigation (select) doesn't remember or share a path. Since there can be many files to select, it required a lot of renavigation to set up inputs.

Add file path memory, and function to drag and drop files if possible.

**Comment by OmegaDroid** [comment]
How should this work? Start from the dir of the last file opened or always start with the config file dir if one is opened? I think probably the former since if you are opening multiple data files they will likely be in the same place.

**Comment by stufraser1** [comment]
Agree - dir of last opened file. Would it open at the location of the
config file when first opened though?

**Comment by jdwpeterson** [comment]
Selecting files in the config tabs should now open in the last directory.
