### ISSUE TITLE
UI - config set up

### ISSUE THREAD

**Issue by stufraser1** [OasisLMF/OpenDataTransform#64]
Improvements to setting config information:

- [ ] Display config file name to show what was loaded
- [ ] "Template" tab is confusing. Users thought it was needed - remove in favour of Loc, Acc, RI tabs only
- [ ] Allow user to open a config file only. Opening a mapping file doesn't work but not clear why

**Comment by jdwpeterson** [comment]
- The config file name should be shown in the ui menu bar.
- The Template tab has been hidden although the code behind it is still there so can be turned back on if required.
- Some simple validation has been added when opening a config file to check that a `transformations` key is present in the file.
