### ISSUE TITLE
EXE - process message

### ISSUE THREAD

**Issue by stufraser1** [OasisLMF/OpenDataTransform#67]
When the EXE file is run, a black window appears with no message. User experience shows this is confusing as sometimes it takes a minute or more for the UI window to open:

Add a message to tell users that the EXE is working / opening, please wait....

**Comment by jdwpeterson** [comment]
https://pyinstaller.org/en/v4.7/usage.html?highlight=splash#splash-screen-experimental allows you to add a splash screen to pyinstaller but is incompatible with mac os

**Comment by jdwpeterson** [comment]
@stufraser1 We've managed to get a splash screen image showing while the app is loading (non mac only).  We've used a basic loading icon - https://github.com/OasisLMF/OpenDataTransform/blob/feature/splash-screen/splashfile.png but can change this if you have an image you prefer

**Comment by jdwpeterson** [comment]
This has been implemented for non mac uses with the image above.
